services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Wexample\SymfonyWex\:
        resource: '../../{Form,Repository,Service}'

    Wexample\SymfonyWex\Controller\:
        resource: '../../Controller/'
        exclude: '../../Controller/**/Abstract*.php'
        tags: ['controller.service_arguments']

    Wexample\PhpWex\Common\WexClient:
        arguments:
            $binary: '%wexample_symfony_wex.binary%'
            $workingDirectory: '%wexample_symfony_wex.working_directory%'
            $timeout: '%wexample_symfony_wex.timeout%'
